# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKX-BynQx5bHaWpt7I2jMy5WB0jw3_HT
"""

def maximumPeople(population, location, cloud_location, cloud_range):
    n = len(population)
    m = len(cloud_location)

    # Initialize an array to keep track of sunny towns
    sunny = [True] * n

    # Mark towns covered by clouds
    for i in range(m):
        for j in range(n):
            if abs(cloud_location[i] - location[j]) <= cloud_range[i]:
                sunny[j] = False

    # Calculate the initial number of people in sunny towns
    initial_sunny_people = sum(population[i] for i in range(n) if sunny[i])

    max_sunny_people = initial_sunny_people

    # Try removing each cloud
    for i in range(m):
        temp_sunny = sunny.copy()
        for j in range(n):
            if abs(cloud_location[i] - location[j]) <= cloud_range[i]:
                temp_sunny[j] = True

        # Check if any other cloud covers this town
        for k in range(m):
            if k != i:
                for j in range(n):
                    if abs(cloud_location[k] - location[j]) <= cloud_range[k]:
                        temp_sunny[j] = False

        sunny_people = sum(population[j] for j in range(n) if temp_sunny[j])
        max_sunny_people = max(max_sunny_people, sunny_people)

    return max_sunny_people

def main():
    print("Welcome cloudy day  problem!")

    # Input number of towns
    n = int(input("Enter the number of towns: "))

    # Input population of towns
    print("Enter the population of each town (space-separated):")
    population = list(map(int, input().split()))

    # Input location of towns
    print("Enter the location of each town (space-separated):")
    location = list(map(int, input().split()))

    # Input number of clouds
    m = int(input("Enter the number of clouds: "))

    # Input location of clouds
    print("Enter the location of each cloud (space-separated):")
    cloud_location = list(map(int, input().split()))

    # Input range of clouds
    print("Enter the range of each cloud (space-separated):")
    cloud_range = list(map(int, input().split()))

    # Call the function and print the result
    result = maximumPeople(population, location, cloud_location, cloud_range)
    print(f"\nThe maximum number of people that will be in sunny towns after removing one cloud is: {result}")

if __name__ == "__main__":
    main()