# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dMjfrPSSO0z-PvYmUgmkppKjz8Dk2z2
"""

def quickSort(pivot, arr):
    left = []
    equal = []
    right = []

    for num in arr:
        if num < pivot:
            left.append(num)
        elif num > pivot:
            right.append(num)
        else:
            equal.append(num)

    return left + equal + right

def main():
    print("Welcome to the Quicksort Partition Example")
    print("=========================================")

    # Read input size and array
    n = int(input("Enter the size of the array: "))
    arr = list(map(int, input(f"Enter {n} space-separated integers: ").strip().split()))

    # Ensure correct input size
    if len(arr) != n:
        print("Error: Input size does not match the specified size")
        return

    # Select pivot element (in this case, the first element)
    pivot = arr[0]

    # Perform partitioning
    result = quickSort(pivot, arr)

    # Display the sorted array
    print("\nSorted Array:")
    print(" ".join(map(str, result)))

if __name__ == "__main__":
    main()